language: node_js
os:
  - osx
  - linux
node_js: 18

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
script:
  - |
    echo ">>> Run integration test"
    npm install && npm run compile && npm run coverage_travis
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
cache: npm